language: php

php:
  - 7.2

sudo: false

env:
  - APP_DEBUG=false

before_install:
  - mysql -e 'CREATE DATABASE laravelcms_test;'

before_script:
  - cp .travis.env .env
  - composer self-update
  - composer install --prefer-source --no-interaction --dev
  - php artisan migrate

install:
  - composer install --prefer-dist --quiet

script:
  - vendor/bin/phpunit

services:
  - mysql

notifications:
  email: false
