language: php

php:
  - 7.2

sudo: false
env:
  matrix:
    - LARAVEL_VERSION=5.5.*
    - LARAVEL_VERSION=5.6.*
    - LARAVEL_VERSION=5.7.*
    - LARAVEL_VERSION=5.8.*
    - LARAVEL_VERSION=6.*
    - APP_DEBUG=false

matrix:
  fast_finish: true

before_install:
  - mysql -e 'CREATE DATABASE laravelcms_test;'

before_script:
  - cp .travis.env .env
  - composer self-update
  - composer require "illuminate/support:${LARAVEL_VERSION}"
  - composer require "laravel/laravel:${LARAVEL_VERSION}"
  - composer show laravel/framework
  - composer install --prefer-source --no-interaction --dev
  - php artisan migrate

install:
  - composer install --prefer-dist --quiet

script:
  - vendor/bin/phpunit

services:
  - mysql

notifications:
  email: false
