language: php

php:
  - 7.2

sudo: false
env:
  matrix:
    - LARAVEL_VERSION=5.*
    - LARAVEL_VERSION=6.*

matrix:
  fast_finish: true

before_install:
  - mysql -e 'CREATE DATABASE laravelcms_test;'

before_script:
  - composer self-update
  - composer create-project --prefer-dist laravel/laravel cms "${LARAVEL_VERSION}"
  - cd cms
  - composer show laravel/framework
  - cp -f ../.travis.env .env
  - composer require alexstack/laravel-cms dev-alex_dev
  - php artisan laravelcms --action=initialize --locale=en --table_prefix=cms_

install:
  - composer install --prefer-dist --quiet

script:
  - vendor/bin/phpunit

services:
  - mysql

notifications:
  email: false
